import { User, Task, DailyWorkLog, TokenTransaction, RewardClaim } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin',
    username: 'admin',
    password: 'password',
    name: 'Bureau Administrator',
    email: 'admin@dailybureau.org',
    role: 'admin',
    title: 'Chief Bureau Administrator & Master Inspector',
    department: 'Dispatch & Logistics',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    deskNumber: 'Office No. 01 — Executive Quarters',
    signature: 'E. Sterling, Bureau Chief',
    createdAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'usr-1',
    username: 'arthur',
    password: 'password',
    name: 'Arthur Pendelton',
    email: 'arthur.p@dailybureau.org',
    role: 'member',
    title: 'Master Horologist & Lead Artisan',
    department: 'Atelier & Craft',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    deskNumber: 'Desk No. 04 — North Bay',
    signature: 'A. Pendelton, M.H.',
    createdAt: '2026-09-02T09:00:00Z',
  },
  {
    id: 'usr-2',
    username: 'clara',
    password: 'password',
    name: 'Clara Oswald',
    email: 'clara.o@dailybureau.org',
    role: 'member',
    title: 'Systems Dispatcher & Chrono-Engineer',
    department: 'Systems & Engineering',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    deskNumber: 'Desk No. 09 — Foundry Wing',
    signature: 'C. Oswald, Eng.',
    createdAt: '2026-09-03T10:00:00Z',
  },
  {
    id: 'usr-3',
    username: 'julian',
    password: 'password',
    name: 'Julian Hayes',
    email: 'julian.h@dailybureau.org',
    role: 'member',
    title: 'Principal Archivist & Chronicler',
    department: 'Archives & Research',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    deskNumber: 'Desk No. 12 — Vault Stack B',
    signature: 'J. Hayes, F.R.S.',
    createdAt: '2026-09-04T11:00:00Z',
  },
];

export const INITIAL_TASKS: Task[] = [
  // Arthur's Daily Tasks
  {
    id: 'tsk-101',
    orderNumber: 1041,
    itemType: 'task',
    title: 'Calibrate Mainspring Escapement for Tower Chronometer',
    description: 'Disassemble central balance wheel, polish ruby pallets, and adjust tension springs.',
    assigneeId: 'usr-1',
    createdById: 'usr-1',
    createdByUsername: 'arthur',
    priority: 'opus',
    status: 'completed',
    category: 'Mechanics & Precision',
    reminderTime: '10:00',
    estimatedHours: 6.5,
    spentHours: 6.0,
    subtasks: [
      { id: 'sub-1', title: 'Dismantle escapement housing', completed: true },
      { id: 'sub-2', title: 'Clean jeweled bearings', completed: true },
    ],
    dueDate: '2026-09-13',
    createdAt: '2026-09-12T08:30:00Z',
    completedAt: '2026-09-13T14:15:00Z',
    completedBy: 'arthur',
    adminSignedOff: true,
    adminSignedAt: '2026-09-13T15:00:00Z',
    adminSignedBy: 'usr-admin',
    adminNotes: 'Precision verified to observatory standard.',
  },
  {
    id: 'tsk-102',
    orderNumber: 1042,
    itemType: 'task',
    title: 'Finalize Brass Ingot Metallurgical Registry',
    description: 'Record density and tensile ratings for consignment batch #B-77 from the Sheffield foundry.',
    assigneeId: 'usr-1',
    createdById: 'usr-1',
    createdByUsername: 'arthur',
    priority: 'routine',
    status: 'pending',
    category: 'Atelier & Craft',
    reminderTime: '14:30',
    estimatedHours: 3.0,
    subtasks: [
      { id: 'sub-4', title: 'Weigh ingots on hydrostatic scale', completed: false },
    ],
    dueDate: '2026-09-15',
    createdAt: '2026-09-13T09:00:00Z',
  },
  // Arthur's Daily Routine
  {
    id: 'tsk-102-r',
    orderNumber: 1038,
    itemType: 'routine',
    title: 'Morning Lathe Lubrication & Jeweled Pivot Inspection',
    description: 'Clean watchmaker lathe bed, apply purified sperm-whale oil to high-friction headstock bearings.',
    assigneeId: 'usr-1',
    createdById: 'usr-1',
    createdByUsername: 'arthur',
    priority: 'routine',
    status: 'pending',
    category: 'Atelier & Craft',
    reminderTime: '08:30',
    estimatedHours: 0.5,
    subtasks: [
      { id: 'sub-r1', title: 'Check oil cups', completed: true },
      { id: 'sub-r2', title: 'Verify belt tension', completed: false },
    ],
    dueDate: '2026-09-14',
    createdAt: '2026-09-13T08:00:00Z',
  },
  {
    id: 'tsk-103',
    orderNumber: 1040,
    itemType: 'task',
    title: 'Discarded Requisition: Obsolete Lathe Chucks',
    description: 'Old inventory review that was superseded by new tooling order.',
    assigneeId: 'usr-1',
    createdById: 'usr-1',
    createdByUsername: 'arthur',
    priority: 'routine',
    status: 'deleted',
    category: 'Atelier & Craft',
    estimatedHours: 1.0,
    subtasks: [],
    dueDate: '2026-09-11',
    createdAt: '2026-09-10T09:00:00Z',
    deletedAt: '2026-09-12T10:00:00Z',
    deletedBy: 'arthur',
  },

  // Clara's Daily Task & Routine
  {
    id: 'tsk-104',
    orderNumber: 1043,
    itemType: 'task',
    title: 'Re-index Telegraph Relay Switches & Pneumatic Tubes',
    description: 'Inspect air seals on pneumatic tube stations 4 through 8, ensure electrical contacts are freed of oxidation.',
    assigneeId: 'usr-2',
    createdById: 'usr-2',
    createdByUsername: 'clara',
    priority: 'urgent',
    status: 'completed',
    category: 'Systems & Engineering',
    reminderTime: '11:00',
    estimatedHours: 4.5,
    spentHours: 4.0,
    subtasks: [
      { id: 'sub-6', title: 'Test pneumatic pressure gauge', completed: true },
      { id: 'sub-7', title: 'Rewire brass terminal blocks', completed: true },
    ],
    dueDate: '2026-09-13',
    createdAt: '2026-09-12T11:00:00Z',
    completedAt: '2026-09-13T12:30:00Z',
    completedBy: 'clara',
  },
  {
    id: 'tsk-105',
    orderNumber: 1044,
    itemType: 'task',
    title: 'Draft Telemetry Protocol Specification V2.4',
    description: 'Formulate duplex encoding standards for low-latency dispatch signals between the North Bureau and East Wharf.',
    assigneeId: 'usr-2',
    createdById: 'usr-2',
    createdByUsername: 'clara',
    priority: 'opus',
    status: 'pending',
    category: 'Systems & Engineering',
    reminderTime: '15:00',
    estimatedHours: 8.0,
    subtasks: [
      { id: 'sub-9', title: 'Review parity bit error thresholds', completed: true },
    ],
    dueDate: '2026-09-16',
    createdAt: '2026-09-13T10:15:00Z',
  },
  {
    id: 'tsk-105-r',
    orderNumber: 1037,
    itemType: 'routine',
    title: 'Daily Pneumatic Line Pressure & Galvanometer Calibration',
    description: 'Measure baseline voltage across telegraph line #2 and ensure pressure holds at 45 PSI.',
    assigneeId: 'usr-2',
    createdById: 'usr-2',
    createdByUsername: 'clara',
    priority: 'routine',
    status: 'completed',
    category: 'Systems & Engineering',
    reminderTime: '09:00',
    estimatedHours: 0.75,
    subtasks: [],
    dueDate: '2026-09-14',
    createdAt: '2026-09-13T08:30:00Z',
    completedAt: '2026-09-14T09:15:00Z',
    completedBy: 'clara',
  },
  {
    id: 'tsk-106',
    orderNumber: 1039,
    itemType: 'task',
    title: 'Draft Signal Matrix for Abandoned Cable Line #4',
    description: 'Deprecated route test removed after line decommission.',
    assigneeId: 'usr-2',
    createdById: 'usr-2',
    createdByUsername: 'clara',
    priority: 'routine',
    status: 'deleted',
    category: 'Systems & Engineering',
    estimatedHours: 2.0,
    subtasks: [],
    dueDate: '2026-09-10',
    createdAt: '2026-09-09T14:00:00Z',
    deletedAt: '2026-09-11T16:00:00Z',
    deletedBy: 'clara',
  },

  // Admin Tasks
  {
    id: 'tsk-109',
    orderNumber: 1047,
    itemType: 'task',
    title: 'Quarterly Staff Roster Audit & Desk Allocation',
    description: 'Assess workstation ventilation and inspect mechanical stampers for ink depletion.',
    assigneeId: 'usr-admin',
    createdById: 'usr-admin',
    createdByUsername: 'admin',
    priority: 'routine',
    status: 'pending',
    category: 'Dispatch & Logistics',
    reminderTime: '09:30',
    estimatedHours: 4.0,
    subtasks: [],
    dueDate: '2026-09-18',
    createdAt: '2026-09-13T08:00:00Z',
  },
  {
    id: 'tsk-109-r',
    orderNumber: 1036,
    itemType: 'routine',
    title: 'Morning Master Ledger Synchrony & Telegraph Dispatch Log',
    description: 'Review morning dispatches across all workstations and stamp open requisitions.',
    assigneeId: 'usr-admin',
    createdById: 'usr-admin',
    createdByUsername: 'admin',
    priority: 'opus',
    status: 'pending',
    category: 'Dispatch & Logistics',
    reminderTime: '08:00',
    estimatedHours: 0.5,
    subtasks: [],
    dueDate: '2026-09-14',
    createdAt: '2026-09-13T07:45:00Z',
  }
];

export const INITIAL_LOGS: DailyWorkLog[] = [
  {
    id: 'log-201',
    logNumber: 441,
    userId: 'usr-1',
    date: '2026-09-13',
    accomplishments: [
      'Completed overhaul on Tower Chronometer balance escapement (Task #1041).',
      'Checked batch samples for Sheffield brass ingots.',
    ],
    blockers: 'Awaiting delivery of specialized jewel pivot lubricant.',
    nextFocus: 'Complete entry for metallurgical ledger.',
    hoursLogged: 7.5,
    submittedAt: '2026-09-13T17:30:00Z',
  },
];

export const INITIAL_TOKEN_TRANSACTIONS: TokenTransaction[] = [
  {
    id: 'tx-100',
    userId: 'usr-1',
    username: 'arthur',
    amount: 275,
    rupeeValue: 550,
    type: 'bonus',
    description: 'Master Craftsman Fellowship Bounty & Accrued Stamped Orders',
    timestamp: '2026-09-12T08:00:00Z',
  },
  {
    id: 'tx-101',
    userId: 'usr-1',
    username: 'arthur',
    amount: 1,
    rupeeValue: 2,
    type: 'earned',
    taskId: 'tsk-101',
    taskTitle: 'Overhaul Clockwork Movement for Tower Chronometer #4',
    description: 'Task completion bounty',
    timestamp: '2026-09-13T14:30:00Z',
  },
  {
    id: 'tx-103',
    userId: 'usr-2',
    username: 'clara',
    amount: 140,
    rupeeValue: 280,
    type: 'earned',
    description: 'Pneumatic Tube & Dispatch Calibration Bounty',
    timestamp: '2026-09-13T11:45:00Z',
  },
  {
    id: 'tx-104',
    userId: 'usr-3',
    username: 'julian',
    amount: 80,
    rupeeValue: 160,
    type: 'earned',
    description: 'Archival Transcription & Ledger Restoration Bounty',
    timestamp: '2026-09-12T16:30:00Z',
  },
];

export const INITIAL_REWARD_CLAIMS: RewardClaim[] = [
  {
    id: 'claim-501',
    claimNumber: 701,
    userId: 'usr-2',
    username: 'clara',
    userName: 'Clara Oswald',
    tokensRedeemed: 250,
    rupeeAmount: 500,
    payoutMethod: 'upi',
    payoutDetails: 'clara.oswald@okhdfcbank',
    status: 'approved',
    requestedAt: '2026-09-13T12:00:00Z',
    reviewedAt: '2026-09-13T12:30:00Z',
    reviewedBy: 'admin',
    adminNotes: 'Disbursed ₹500 via Bureau Instant UPI Gateway.',
  },
];


